export interface StudentsParameters {
	id: number;
	name: string;
	socialName: string;
	preferredName: string;
	ismartEmail: string;
	phoneNumber: string;
	gender: string;
	sexualOrientation: string;
	raceEthnicity: string;
	hasDisability: boolean;
	linkedin: string;
	transferredCourseOrUniversity: boolean;
	transferDate: string;
	currentCourseStart: string;
	currentCourseStartYear: number;
	currentCourseEnd: string;
	currentCourseEndYear: number;
	supportedCourseFormula: string;
	currentArea: string;
	universityType: string;
	currentAggregatedCourse: string;
	currentDetailedCourse: string;
	currentDetailedUniversity: string;
	currentCity: string;
	currentState: string;
	currentCountry: string;
	currentAggregatedLocation: string;
	currentShift: string;
	holderContractStatus: string;
	realStatus: string;
	realProfile: string;
	hrProfile: string;
	targetStatus: string;
	entryProgram: string;
	projectYears: number;
	entryYearClass: string;
	schoolNetwork: string;
	school: string;
	standardizedSchool: string;
	groupedLocation: string;
	specificLocation: string;
	duplicatedTargetStatus: string;
	duplicatedCurrentStatus: string;
	targetAudience: string;
	working: boolean;
	opportunityType: string;
	details: string;
	sector: string;
	careerTrack: string;
	organization: string;
	website: string;
	startDate: string;
	endDate: string;
	compensation: string;
	partnerCompanies: string;
	topGlobalCompanies: string;
	comments: string;
	tag: string;
	jan: string;
	feb: string;
	mar: string;
	apr: string;
	may: string;
	jun: string;
	jul: string;
	aug: string;
	sep: string;
	oct: string;
	nov: string;
	dec: string;
	january: string;
	february: string;
	march: string;
	april: string;
	mayFull: string;
	june: string;
	july: string;
	august: string;
	september: string;
	october: string;
	november: string;
	december: string;
	january2: string;
	february2: string;
	march2: string;
	april2: string;
	may2: string;
	june2: string;
	july2: string;
	august2: string;
	september2: string;
	october2: string;
	november2: string;
	december2: string;
	internshipUnavailabilityReason: string;
	careerTrajectoryInterests: string;
	primaryInterest: string;
	secondaryInterest: string;
	intendedWorkingAreas: string;
	additionalAreaInterests: string;
	seekingProfessionalOpportunity: string;
	opportunitiesLookingFor: string;
	opportunityDetails: string;
	languages: string;
	technicalKnowledge: string;
	officePackageKnowledge: string;
	wordProficiencyLevel: string;
	excelProficiencyLevel: string;
	powerPointProficiencyLevel: string;
}

export interface StudentsResponse {
	data: StudentsParameters[];
}

export interface StudentsStats {
	total: number;
	working: number;
	notWorking: number;
	avgCompensation: string;
}

export interface StudentsType {
	$limit?: number;
	$skip?: number;
	[key: string]:
		| boolean
		| string
		| number
		| undefined
		| null
		| { $regex: RegExp; $options?: string };
}
